### ISSUE TITLE
Extract sheet.js into it's own package

### ISSUE THREAD

**Issue by k15a** [threepointone/glamor#246] opened 2017-04-18 17:39 UTC
Hey,

as styled-components and probably many others are using glamor to inject the styles into the DOM it would be probably pretty great to extract the [insertion mechanism](https://github.com/threepointone/glamor/blob/master/src/sheet.js) into it's own package.
This would be great so all issues like [styled-components#707](https://github.com/styled-components/styled-components/pull/707) could be solved at a single place.

Maybe we could get the [`sheet` package name](https://www.npmjs.com/package/sheet) from @gather.

I am happy to help with this.

**Comment by ChristopherBiscardi** [comment] 2017-04-18 22:08
dupe of #242. I'd encourage conversation there instead.

**Closed by ChristopherBiscardi** 2017-04-18 22:08 UTC
