### ISSUE TITLE
Labels are somehow broken in prod

### ISSUE THREAD

**Issue by otbe** [threepointone/glamor#139] opened 2016-12-01 18:25 UTC
Hi,

I guess labels are somehow broken. In dev builds all seems to work fine, but in production I get this exception: ```Uncaught TypeError: e.label.join is not a function(…)```. The root cause is [here](https://github.com/threepointone/glamor/blob/master/src/index.js#L363)

After some debugging it seems that in dev mode label is always an array, but in prod mode the first occurrence of a label is a primitive string, maybe caused by [this](https://github.com/threepointone/glamor/blob/master/src/index.js#L234) ?

Grateful for any hints :)

Thanks!

Glamor: 2.20.8

**Comment by threepointone** [comment] 2016-12-02 02:09
ugh, my bad, will fix in next few hours.

**Comment by threepointone** [comment] 2016-12-02 10:03
could you try out 2.20.9?

**Comment by otbe** [comment] 2016-12-02 10:40
No I get ```Uncaught TypeError: Cannot read property 'composes' of null``` :)
Caused by [this](https://github.com/threepointone/glamor/blob/master/src/index.js#L310)

**Comment by threepointone** [comment] 2016-12-02 10:44
ugh. update and try again?

**Comment by otbe** [comment] 2016-12-02 11:01
```Uncaught TypeError: Cannot convert undefined or null to object``` caused by [this](https://github.com/threepointone/glamor/blob/master/src/index.js#L312)

**Comment by threepointone** [comment] 2016-12-02 11:06
ugh I'm such a mess today. I'll write tests later. update and try again? sorry for making you do qa :P

**Comment by otbe** [comment] 2016-12-02 11:33
:D

No problem, glad to help :)

It seems to work now, but some global ```insertRule()```'s wont work anymore. Same game again: in dev mode they work but in prod mode they will not work (without error). I think its related to the speedy mode:

This works only in dev mode
```
insertRule(`html{font-size: ${defaultFontSize};}body{background-color:${defaultBackgroundColor};font-family: ${FONT_FAMILY.sans};text-rendering:optimizeLegibility;}`);
```

This works in both modes
```
insertRule(`html{font-size: ${defaultFontSize};}`);
insertRule(`body{background-color:${defaultBackgroundColor};font-family: ${FONT_FAMILY.sans};text-rendering:optimizeLegibility;}`);
```

And there is another bug, but I will open an issue for this :)

**Comment by threepointone** [comment] 2016-12-02 11:35
That's not a bug, though it needs to be documented better. It was brought up https://github.com/threepointone/glamor/issues/130 Happy to take a PR with better docs for this!

**Comment by otbe** [comment] 2016-12-02 11:44
Thanks!!

**Comment by threepointone** [comment] 2016-12-02 12:13
closing this, do let me know if you have more issues. Thank you muchly!

**Closed by threepointone** 2016-12-02 12:13 UTC
Labels: bug
