### ISSUE TITLE
Integration with hyperscript?

### ISSUE THREAD

**Issue by pyros2097** [threepointone/glamor#123] opened 2016-11-24 16:52 UTC
I'm trying to use this with [hyperscript](https://github.com/dominictarr/hyperscript) which is used in [https://github.com/skatejs/skatejs](skatejs) but it seems its not populating the style tag in head?

```js
var styles = {
  navigation: style({
    fontSize: '15px',
    width: '20em',
    height: '100%',
    color: 'white',
    background: `rgba(0, 0, 0, 1)`,
    position: 'fixed',
    top: '0',
    right: '0',
    bottom: '0',
    zIndex: '2000',
    transition: 'right 0.3s ease-in-out 0s',
  }),
}

skate.h('div', styles.navigation, 'hello')
```

This is how it looks,
![screenshot from 2016-11-24 22-19-58](https://cloud.githubusercontent.com/assets/1687946/20605996/3be730d2-b294-11e6-814d-1539315fd607.png)

**Comment by threepointone** [comment] 2016-11-25 04:32
yes, glamor doesn't have first class support for web components/iframes yet. working on it for v3 though.

**Comment by threepointone** [comment] 2016-11-25 04:34
so what's happening here because you're using te minified version, is it *is* populating in head tag, but using CSSOM so it won't show in the elements tree. further, since it's inside this shadow dom thing, the head css doesn't affect it iirc.

**Comment by threepointone** [comment] 2016-11-25 07:10
duplicate of #38

**Closed by threepointone** 2016-11-25 07:10 UTC
Labels: question

**Comment by treshugart** [comment] 2017-01-19 01:45
Can confirm ^

You need to use the `cssFor` named export for your styles:

```js
import { cssFor, style } from 'glamor';

// your styles
const css = style({ ... });

// and later in renderCallback()...
<style>{cssFor(css)}</style>
<div {...css} />
```
