### ISSUE TITLE
`WeakMap` console warning when `0` used as conditional

### ISSUE THREAD

**Issue by green-arrow** [threepointone/glamor#251] opened 2017-05-08 20:14 UTC
When using a falsey value other than `null`, `undefined`, or `false` (like `0`), there is a console warning:

```
failed setting the WeakMap cache for args
this should NOT happen, please file a bug on the github repo.
```

Example sandbox:

[![Edit Glamor WeakMap Error](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/71wn6Orj)

**Comment by otbe** [comment] 2017-05-12 08:30
Confirmed. Will be fixed after v3 release

**Comment by threepointone** [comment] 2017-07-19 10:21
why are you sending 0 in the first place? I don't think we should special case for this unless there's a good reason. closing, feel free to reopen if I"m wrong.

**Closed by threepointone** 2017-07-19 10:21 UTC
Labels: after-v3

**Comment by green-arrow** [comment] 2017-07-19 11:37
@threepointone - I was conditionally applying a style based on a number. Something like `numNotifications && styles.badgeVisible`. 

The only reason I filed this bug is because I read in the documentation that any falsey values will be ignored in calls to `css`. I think it’s fine if `0` isn’t supported since it’s easy enough to do a true Boolean comparison, but the documentation should reflect that. I’d be happy to open a PR on the docs if you want :smile:

Thanks for all your work on this project, it really is a joy to use!

**Comment by green-arrow** [comment] 2017-07-19 11:45
Now that I’m reading the docs again, I can’t find the reference to doing conditional styling in a call to `css`. Not sure if it was removed or I’m just remembering completely wrong, so take the previous comment with a grain of salt 😝

**Comment by threepointone** [comment] 2017-07-19 12:11
no worries. in general I don't think glamor should handle 0, because it points to some underlying problem with the code (eg - it'll fail with 1, but pass on 0, but both probably mean you're sending the wrong thing to glamor)
